# Generated by Django 5.0.7 on 2024-09-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DT_project', '0002_rooftype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stories', models.CharField(max_length=100)),
            ],
        ),
    ]
