# Generated by Django 5.0.7 on 2024-09-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DT_project', '0003_stories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stories',
            new_name='Storey',
        ),
    ]
