# Generated by Django 5.0.7 on 2024-09-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DT_project', '0004_rename_stories_storey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill', models.CharField(max_length=100)),
            ],
        ),
    ]
