# Generated by Django 5.0.7 on 2024-09-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DT_project', '0005_electricity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity',
            name='Bill',
            field=models.IntegerField(),
        ),
    ]
